# Generated by Django 4.1.2 on 2022-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('completed_yes_no', models.BooleanField()),
            ],
        ),
    ]
