# Generated by Django 4.1.2 on 2022-10-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='completed_yes_no',
            new_name='item_completed',
        ),
    ]
