# Generated by Django 4.1.2 on 2022-10-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grocery_list', '0002_rename_completed_yes_no_groceryitem_item_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='item_completed',
            field=models.BooleanField(default=False),
        ),
    ]
