# Generated by Django 4.1.2 on 2022-10-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grocery_list', '0003_alter_groceryitem_item_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='item_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
