# Generated by Django 4.1.2 on 2022-10-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grocery_list', '0004_groceryitem_item_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='item_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='item_deleted',
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
