# Generated by Django 4.1.3 on 2022-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cohort', models.CharField(max_length=20)),
                ('favorite_topic', models.CharField(max_length=20)),
                ('favorite_teacher', models.CharField(max_length=20)),
                ('capstone', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
