# Generated by Django 4.1.3 on 2022-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cohort', models.CharField(max_length=30)),
                ('favorite_topic', models.CharField(max_length=30)),
                ('favorite_teacher', models.CharField(max_length=30)),
                ('capstone', models.CharField(max_length=30)),
            ],
        ),
    ]
