# Generated by Django 4.1.4 on 2022-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Cohort', models.CharField(max_length=50)),
                ('Favorite_topic', models.CharField(max_length=50)),
                ('Favorite_teacher', models.CharField(max_length=50)),
                ('Capstone', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
