# Generated by Django 4.1.4 on 2022-12-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-Last_name']},
        ),
    ]
