# Generated by Django 4.1.3 on 2022-11-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='capstone',
            field=models.URLField(max_length=500),
        ),
    ]
