# Generated by Django 4.1.3 on 2022-11-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_text', models.CharField(max_length=200)),
                ('shortened_code', models.CharField(max_length=200)),
            ],
        ),
    ]
