# Generated by Django 4.1.3 on 2022-11-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
