# Generated by Django 4.1.3 on 2022-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_alter_url_shortened_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
