# Generated by Django 4.1.2 on 2022-10-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceries',
            name='grocery_list',
        ),
    ]
