# Generated by Django 4.1.2 on 2022-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='complete_task',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='completed_date',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
