# Generated by Django 4.1.2 on 2022-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_remove_groceryitem_complete_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(default='2022-10-22'),
        ),
    ]
