# Generated by Django 4.1.2 on 2022-10-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_alter_groceryitem_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
