# Generated by Django 4.1.2 on 2022-10-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_groceryitem_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='complete_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 21, 32, 741701, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 21, 32, 740705, tzinfo=datetime.timezone.utc)),
        ),
    ]
