# Generated by Django 4.1.2 on 2022-10-24 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0005_groceryitem_complete_date2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='complete_date2',
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 23, 56, 723800, tzinfo=datetime.timezone.utc)),
        ),
    ]
