# Generated by Django 4.1.2 on 2022-10-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField()),
            ],
        ),
    ]
