# Generated by Django 4.1.2 on 2022-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed_check',
            field=models.IntegerField(default=0),
        ),
    ]
