# Generated by Django 4.1.2 on 2022-10-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_groceryitem_completed_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_check',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
