# Generated by Django 4.1.3 on 2022-11-29 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_remove_groceryitem_completed_groceryitem_list_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 45, 26, 884362, tzinfo=datetime.timezone.utc)),
        ),
    ]
