# Generated by Django 4.1.3 on 2022-11-29 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0003_groceryitem_completed_groceryitem_completed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='list_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
