# Generated by Django 4.1.2 on 2022-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chirp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chirpapp", name="chirp", field=models.CharField(max_length=200),
        ),
    ]
