# Generated by Django 4.1.2 on 2022-10-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chirp", "0002_alter_chirpapp_chirp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chirpapp", name="chirp", field=models.TextField(max_length=200),
        ),
    ]
