# Generated by Django 4.1.2 on 2022-10-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_posts_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
