# Generated by Django 4.1.2 on 2022-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_post_post_created_on_post_post_text_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=200),
        ),
    ]
