# Generated by Django 4.1.2 on 2022-11-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_rename_shorturl_urlshortener'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlShortener',
            new_name='ShortURL',
        ),
    ]
