# Generated by Django 4.1.2 on 2022-11-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_rename_shorturl_urlshortener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='url',
            field=models.URLField(max_length=350),
        ),
    ]
