# Generated by Django 4.1.2 on 2022-10-18 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 21, 42, 21, 680595, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
