# Generated by Django 4.1.2 on 2022-10-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('creation_ip', models.CharField(max_length=200)),
                ('clicks', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=200)),
                ('click_time', models.DateTimeField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='short_url.url')),
            ],
        ),
    ]
