# Generated by Django 4.1.2 on 2022-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='user_ip',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
