# Generated by Django 4.1.2 on 2022-10-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='click_time',
        ),
    ]
