# Generated by Django 4.1.2 on 2022-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_url_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
