# Generated by Django 4.1.2 on 2022-10-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0003_url_clicks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user_ip',
            new_name='creation_ip',
        ),
    ]
