# Generated by Django 4.1.3 on 2022-11-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Urls',
        ),
    ]
