# Generated by Django 4.1.3 on 2022-11-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0003_remove_urls_short_url_urls_short_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
