# Generated by Django 4.1.2 on 2022-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.CharField(max_length=200)),
                ("short_url", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
