# Generated by Django 4.1.2 on 2022-10-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codestorage", name="long_url", field=models.URLField(),
        ),
    ]
