# Generated by Django 4.1.3 on 2022-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
