# Generated by Django 4.1.2 on 2022-10-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_users_delete_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
