# Generated by Django 3.2 on 2022-12-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='caught_by',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
    ]
