# Generated by Django 4.1.2 on 2022-10-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='chirper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chirp',
            name='chirp',
            field=models.CharField(max_length=200),
        ),
    ]
