# Generated by Django 4.1.2 on 2022-11-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(max_length=10)),
                ('orignal_url', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
