# Generated by Django 4.1.2 on 2022-11-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UrlShortener',
        ),
    ]
