# Generated by Django 4.1.2 on 2022-11-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_shorturl_delete_urlshortener'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortURL',
            new_name='UrlShortener',
        ),
    ]
