# Generated by Django 4.1.2 on 2022-11-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_rename_urlshortener_shorturl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortURL',
            new_name='UrlShortener',
        ),
    ]
