# Generated by Django 4.1.2 on 2022-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteGroceryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=25)),
                ('item_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncompleteGroceryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='grocerylistitem',
            name='grocery_item',
        ),
        migrations.RemoveField(
            model_name='grocerylistitem',
            name='grocery_list',
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
        migrations.DeleteModel(
            name='GroceryList',
        ),
        migrations.DeleteModel(
            name='GroceryListItem',
        ),
    ]
