# Generated by Django 4.1.2 on 2022-10-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
