# Generated by Django 4.1.2 on 2022-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlapp',
            name='short_url',
            field=models.CharField(max_length=6),
        ),
    ]
