# Generated by Django 4.1.2 on 2022-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_completegroceryitems_groceryitems_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteGroceryItems',
        ),
        migrations.DeleteModel(
            name='IncompleteGroceryItems',
        ),
        migrations.AddField(
            model_name='groceryitems',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitems',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitems',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
