# Generated by Django 4.1.3 on 2022-11-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='capstone',
            field=models.URLField(blank=True, null=True),
        ),
    ]
